language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.3
    - android-30
    - android-29

licenses:
  - android-sdk-license-.+

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew bintrayUpload